local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }

-- Main keymaps from Kickstart
keymap('n', '<Esc>', '<cmd>nohlsearch<CR>')
keymap('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
keymap('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })

-- WARNING: Disable arrow keys in normal mode for advanced level practicing
keymap('n', '<left>', '<cmd>echo "Use h to move!!"<CR>')
keymap('n', '<right>', '<cmd>echo "Use l to move!!"<CR>')
keymap('n', '<up>', '<cmd>echo "Use k to move!!"<CR>')
keymap('n', '<down>', '<cmd>echo "Use j to move!!"<CR>')

-- Keybinds to make split navigation easier.
keymap('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
keymap('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
keymap('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
keymap('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })

-- BUFFER NAVIGATION (VS Code: Ctrl+Tab)
keymap('n', '<S-l>', ':BufferLineCycleNext<CR>', opts) -- Shift+L = next buffer
keymap('n', '<S-h>', ':BufferLineCyclePrev<CR>', opts) -- Shift+H = prev buffer
keymap('n', '<leader>x', ':bdelete<CR>', opts) -- Close buffer
keymap('n', '<leader>X', ':bufdo bd<CR>', opts) -- Close all buffers

-- BETTER EDITING
keymap('n', '<C-s>', ':w<CR>', opts) -- Save (Ctrl+S)
keymap('i', '<C-s>', '<Esc>:w<CR>a', opts) -- Save in insert mode

-- Cusom keymaps for Nicolass-Mac-Studio
keymap('n', 'gH', '0', { desc = 'Go to absolute start of line' })
keymap('n', 'gh', '^', { desc = 'Go to first non-blank charter' })
keymap('n', 'gl', 'g_', { desc = 'Go to last non-blank character' })
keymap('n', 'gL', '$', { desc = 'Go to absolute end of line' })

-- Angular-specific navigation for HTML templates
keymap('n', '<leader>ac', function()
  -- Jump to corresponding TypeScript component
  local current_file = vim.fn.expand('%:p')
  if current_file:match('%.html$') then
    local ts_file = current_file:gsub('%.html$', '.ts')
    if vim.fn.filereadable(ts_file) == 1 then
      vim.cmd('edit ' .. ts_file)
    else
      print('No matching .ts file found')
    end
  elseif current_file:match('%.ts$') then
    local html_file = current_file:gsub('%.ts$', '.html')
    if vim.fn.filereadable(html_file) == 1 then
      vim.cmd('edit ' .. html_file)
    else
      print('No matching .html file found')
    end
  end
end, { desc = '[A]ngular: Toggle [C]omponent/Template' })

-- Search for word under cursor across project (fallback for LSP)
keymap('n', '<leader>aG', function()
  Snacks.picker.grep_word()
end, { desc = '[A]ngular: [G]rep word under cursor' })

-- macOS-style text editing keybindings for insert mode (configured in Ghostty)
-- Cmd + Arrow keys (line navigation)
keymap('i', '<C-Right>', '<End>', { desc = 'Go to end of line' })
keymap('i', '<C-Home>', '<Home>', { desc = 'Go to start of line' })

-- Cmd + Shift + Arrow keys (line selection)
keymap('i', '<C-S-Right>', '<Esc>v$', { desc = 'Select to end of line' })
keymap('i', '<C-S-Left>', '<Esc>v0', { desc = 'Select to start of line' })

-- Option + Arrow keys (word navigation) - using emacs-style sequences
keymap('i', '<M-f>', '<C-o>w', { desc = 'Go forward one word' })
keymap('i', '<M-b>', '<C-o>b', { desc = 'Go back one word' })

-- Option + Shift + Arrow keys (word selection)
keymap('i', '<M-S-Right>', '<Esc>vw', { desc = 'Select forward one word' })
keymap('i', '<M-S-Left>', '<Esc>vb', { desc = 'Select back one word' })

-- Snacks.picker keymaps
-- Top Pickers & Explorer
keymap('n', '<leader><space>', function()
  Snacks.picker.smart()
end, { desc = 'Smart Find Files' })
keymap('n', '<leader>,', function()
  Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap('n', '<leader>:', function()
  Snacks.picker.command_history()
end, { desc = 'Command History' })
-- find
keymap('n', '<leader>fb', function()
  Snacks.picker.buffers()
end, { desc = 'Buffers' })
keymap('n', '<leader>fc', function()
  Snacks.picker.files({ cwd = vim.fn.stdpath('config') })
end, { desc = 'Find Config File' })
keymap('n', '<leader>fg', function()
  Snacks.picker.git_files()
end, { desc = 'Find Git Files' })
keymap('n', '<leader>fp', function()
  Snacks.picker.projects()
end, { desc = 'Projects' })
keymap('n', '<leader>fr', function()
  Snacks.picker.recent({ filter = { cwd = true } })
end, { desc = 'Recent' })
-- git
keymap('n', '<leader>gb', function()
  Snacks.picker.git_branches()
end, { desc = 'Git Branches' })
keymap('n', '<leader>gl', function()
  Snacks.picker.git_log()
end, { desc = 'Git Log' })
keymap('n', '<leader>gL', function()
  Snacks.picker.git_log_line()
end, { desc = 'Git Log Line' })
keymap('n', '<leader>gs', function()
  Snacks.picker.git_status()
end, { desc = 'Git Status' })
keymap('n', '<leader>gS', function()
  Snacks.picker.git_stash()
end, { desc = 'Git Stash' })
keymap('n', '<leader>gd', function()
  Snacks.picker.git_diff()
end, { desc = 'Git Diff (Hunks)' })
keymap('n', '<leader>gf', function()
  Snacks.picker.git_log_file()
end, { desc = 'Git Log File' })
-- Grep
keymap('n', '<leader>sb', function()
  Snacks.picker.lines()
end, { desc = 'Buffer Lines' })
keymap('n', '<leader>sB', function()
  Snacks.picker.grep_buffers()
end, { desc = 'Grep Open Buffers' })
keymap('n', '<leader>sg', function()
  Snacks.picker.grep()
end, { desc = 'Grep' })
keymap({ 'n', 'x' }, '<leader>sw', function()
  Snacks.picker.grep_word()
end, { desc = 'Visual selection or word' })
-- search
keymap('n', '<leader>s"', function()
  Snacks.picker.registers()
end, { desc = 'Registers' })
keymap('n', '<leader>s/', function()
  Snacks.picker.search_history()
end, { desc = 'Search History' })
keymap('n', '<leader>sa', function()
  Snacks.picker.autocmds()
end, { desc = 'Autocmds' })
keymap('n', '<leader>sc', function()
  Snacks.picker.command_history()
end, { desc = 'Command History' })
keymap('n', '<leader>sC', function()
  Snacks.picker.commands()
end, { desc = 'Commands' })
keymap('n', '<leader>sd', function()
  Snacks.picker.diagnostics()
end, { desc = 'Diagnostics' })
keymap('n', '<leader>sD', function()
  Snacks.picker.diagnostics_buffer()
end, { desc = 'Buffer Diagnostics' })
keymap('n', '<leader>sh', function()
  Snacks.picker.help()
end, { desc = 'Help Pages' })
keymap('n', '<leader>sH', function()
  Snacks.picker.highlights()
end, { desc = 'Highlights' })
keymap('n', '<leader>si', function()
  Snacks.picker.icons()
end, { desc = 'Icons' })
keymap('n', '<leader>sj', function()
  Snacks.picker.jumps()
end, { desc = 'Jumps' })
keymap('n', '<leader>sk', function()
  Snacks.picker.keymaps()
end, { desc = 'Keymaps' })
keymap('n', '<leader>sl', function()
  Snacks.picker.loclist()
end, { desc = 'Location List' })
keymap('n', '<leader>sm', function()
  Snacks.picker.marks()
end, { desc = 'Marks' })
keymap('n', '<leader>sM', function()
  Snacks.picker.man()
end, { desc = 'Man Pages' })
keymap('n', '<leader>sp', function()
  Snacks.picker.lazy()
end, { desc = 'Search for Plugin Spec' })
keymap('n', '<leader>sq', function()
  Snacks.picker.qflist()
end, { desc = 'Quickfix List' })
keymap('n', '<leader>sR', function()
  Snacks.picker.resume()
end, { desc = 'Resume' })
keymap('n', '<leader>su', function()
  Snacks.picker.undo()
end, { desc = 'Undo History' })
keymap('n', '<leader>uC', function()
  Snacks.picker.colorschemes()
end, { desc = 'Colorschemes' })
-- LSP
keymap('n', 'gd', function()
  Snacks.picker.lsp_definitions()
end, { desc = 'Goto Definition' })
keymap('n', 'gD', function()
  Snacks.picker.lsp_declarations()
end, { desc = 'Goto Declaration' })
keymap('n', 'gr', function()
  Snacks.picker.lsp_references()
end, { nowait = true, desc = 'References' })
keymap('n', 'gI', function()
  Snacks.picker.lsp_implementations()
end, { desc = 'Goto Implementation' })
keymap('n', 'gy', function()
  Snacks.picker.lsp_type_definitions()
end, { desc = 'Goto T[y]pe Definition' })
keymap('n', 'gai', function()
  Snacks.picker.lsp_incoming_calls()
end, { desc = 'C[a]lls Incoming' })
keymap('n', 'gao', function()
  Snacks.picker.lsp_outgoing_calls()
end, { desc = 'C[a]lls Outgoing' })
keymap('n', '<leader>ss', function()
  Snacks.picker.lsp_symbols()
end, { desc = 'LSP Symbols' })
keymap('n', '<leader>sS', function()
  Snacks.picker.lsp_workspace_symbols()
end, { desc = 'LSP Workspace Symbols' })
-- Code Actions (like Cmd+. in Cursor)
keymap({ 'n', 'v' }, '<leader>ca', vim.lsp.buf.code_action, { desc = '[C]ode [A]ction' })
-- Show diagnostic in floating window
keymap('n', '<leader>cd', vim.diagnostic.open_float, { desc = '[C]ode [D]iagnostic' })
-- File Explorer
keymap('n', '<leader>e', function()
  Snacks.explorer()
end, { desc = 'File Explorer' })
-- Zen Mode
keymap('n', '<leader>z', function()
  Snacks.zen()
end, { desc = 'Toggle Zen Mode' })
keymap('n', '<leader>Z', function()
  Snacks.zen.zoom()
end, { desc = 'Toggle Zoom' })
-- Scratch Buffer
keymap('n', '<leader>.', function()
  Snacks.scratch()
end, { desc = 'Toggle Scratch Buffer' })
keymap('n', '<leader>S', function()
  Snacks.scratch.select()
end, { desc = 'Select Scratch Buffer' })
-- Notification History
keymap('n', '<leader>n', function()
  Snacks.notifier.show_history()
end, { desc = 'Notification History' })
keymap('n', '<leader>bd', function()
  Snacks.bufdelete()
end, { desc = 'Delete Buffer' })
keymap('n', '<leader>cR', function()
  Snacks.rename.rename_file()
end, { desc = 'Rename File' })
keymap({ 'n', 'v' }, '<leader>gB', function()
  Snacks.gitbrowse()
end, { desc = 'Git Browse' })
keymap('n', '<leader>gg', function()
  Snacks.lazygit()
end, { desc = 'Lazygit' })
keymap('n', '<leader>un', function()
  Snacks.notifier.hide()
end, { desc = 'Dismiss All Notifications' })
keymap('n', '<c-/>', function()
  Snacks.terminal()
end, { desc = 'Toggle Terminal' })
keymap('n', '<c-_>', function()
  Snacks.terminal()
end, { desc = 'which_key_ignore' })
keymap({ 'n', 't' }, ']]', function()
  Snacks.words.jump(vim.v.count1)
end, { desc = 'Next Reference' })
keymap({ 'n', 't' }, '[[', function()
  Snacks.words.jump(-vim.v.count1)
end, { desc = 'Prev Reference' })
keymap('n', '<leader>N', function()
  Snacks.win({ file = vim.api.nvim_get_runtime_file('doc/news.txt', false)[1], width = 0.6, height = 0.6, wo = { spell = false, wrap = false, signcolumn = 'yes', statuscolumn = ' ', conceallevel = 3 } })
end, { desc = 'Neovim News' })

-- File search keymaps with Snacks.picker
keymap('n', '<leader>ff', function()
  Snacks.picker.files({ frecency = true })
end, { desc = '[F]ind [f]iles' })
keymap('n', '<leader>sf', function()
  Snacks.picker.files({ frecency = true })
end, { desc = '[S]earch [F]iles (Frecency)' })

-- macOS-style text editing in insert mode
keymap('i', '<D-BS>', '<C-u>', { desc = 'Delete to start of line' }) -- Cmd+Backspace
keymap('i', '<M-BS>', '<C-w>', { desc = 'Delete word backward' }) -- Option+Backspace
keymap('i', '<D-Delete>', '<C-o>D', { desc = 'Delete to end of line' }) -- Cmd+Delete (if you have Del key)

-- macOS-style text selection in insert mode
-- Character selection
keymap('i', '<S-Left>', '<Esc>vh', { desc = 'Select char left' })
keymap('i', '<S-Right>', '<Esc>vl', { desc = 'Select char right' })
keymap('i', '<S-Up>', '<Esc>vk', { desc = 'Select line up' })
keymap('i', '<S-Down>', '<Esc>vj', { desc = 'Select line down' })
